Fix lua template duplicate res error on mac
Fix typo

Fix cmdline fail on new macos

diff --git a/tools/console/bin/adxe b/tools/console/bin/adxe
--- a/tools/console/bin/adxe
+++ b/tools/console/bin/adxe
@@ -3,19 +3,16 @@
 ADXE_CONSOLE_BIN_DIRECTORY=$(dirname "$0")
 ADXE_CONSOLE_BIN_DIRECTORY=$(cd "$ADXE_CONSOLE_BIN_DIRECTORY" && pwd -P)
 
-
-if hash python2 2>/dev/null; then
+if hash python3 2>/dev/null; then
+    PYTHON=python3
+elif hash python2 2>/dev/null; then
     PYTHON=python2
+elif hash python 2>/dev/null; then
+    PYTHON=python
 else
-    if hash python 2>/dev/null; then
-        VERSION="python --version"
-        PYTHON=python
-    else
-        echo "Python 2+ required."
-        exit 1
-    fi
+    echo "Python 2+ required."
+    exit 1
 fi
-
 
 $PYTHON "$ADXE_CONSOLE_BIN_DIRECTORY/adxe.py" "$@"
 
